### PR TITLE
Convert to new-style Pebble Package

### PR DESCRIPTION
**Pull request by cjwilliams**
README still needs to be updated and project needs to be built and published with `pebble build` and `pebble publish`

### CODE REVIEW

**Comment by C-D-Lewis** [comment]
No more test app? 😞

**Comment by cjwilliams** [comment]
Doh, that was silly. I can fix that

**Comment by C-D-Lewis** [comment]
If it's possible, please. I might not need again, but it was useful to have. Maybe again in the future.

**Comment by cjwilliams** [comment]
Done

**Comment by C-D-Lewis** [comment]
👍  Let's give this a whirl

**Pull request merged**
